version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file: ./.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

  client2:
    build:
      context: ./client2
      dockerfile: Dockerfile
    image: myapp-client-2
    container_name: myapp-react-client-2
    depends_on:
      - server
    ports:
      - "3001:3000"
    networks:
      - app-network
   
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-app
    container_name: nginx-app
    ports: 
      - "80:80"
    depends_on:
      - server
      - client
      - client2
    networks:    
      - app-network
      
networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local